#!/bin/python3

import sys

if __name__ == "__main__":
    meal_cost = float(input().strip())
    tip_percent = int(input().strip())
    tax_percent = int(input().strip())
print("The total meal cost is",round(meal_cost*(1+(tip_percent*0.01)+(tax_percent*0.01))) ,"dollars.")
  
