#!/bin/python3
import sys
n = int(input().strip())
iOut,iMaxi = 0,0
while n > 0:
    if n % 2 == 1:
        iOut=iOut+1
        if iOut > iMaxi:
            iMaxi = iOut
    else:
        iOut = 0
    n = n//2
print(iMaxi)
